import pytest
from utils import generate_arrays
from utils import error
import numpy as np
import math

@pytest.mark.parametrize('species, init_conc, expect', [
    (['WT', 'Mutant'], [0.1, 1], {'WT': np.array([0.1, 0, 0]), 'Mutant': np.array([1,0,0])}),
    ([1, 2], [0.5, 5], {1: np.array([0.5, 0, 0]), 2: np.array([5, 0, 0])})
])
def test_generate_arrays(species, init_conc, expect):
    test = generate_arrays(species=species, init_conc=init_conc, dt = 1, minutes = 3)
    
    assert test[species[0]][0] == expect[species[0]][0] and len(test[species[-1]]) == len(expect[species[-1]])
    
@pytest.mark.arametrize('model_values', 'dt', 'minutes', 'expect', [
    (np.array([np.array([0.63818925, 0.95958896, 0.69100166, 0.14828982, 0.56051993, 0.04012196, 0.56075894, 0.43161916, 0.77470217, 0.09058889, 0.80192565, 0.37834343, 0.98484289, 0.8782349 , 0.55870788, 0.74955106, 0.72191231, 0.0350359 , 0.51032689, 0.54592522, 0.87967516, 0.32477201, 0.91998005, 0.95983571, 0.87961044, 0.37581772, 0.67552075, 0.87578561, 0.32481306, 0.06982545, 0.29057004, 0.87619363, 0.97673716, 0.96182672, 0.58984992, 0.20863113, 0.34804359, 0.44877095, 0.84348901, 0.86438217, 0.47576098, 0.85746128, 0.52255269, 0.89076674, 0.70797006, 0.89974225, 0.55057164, 0.2082994 , 0.66722761, 0.96789618, 0.38060714, 0.32865122, 0.93453686, 0.96950417, 0.20853653, 0.16517725, 0.18037798, 0.59515772, 0.42547148, 0.79573015])], [np.array([0.71188763, 0.31823601, 0.54641953, 0.309062  , 0.0212459 , 0.93177561, 0.17228215, 0.42693282, 0.40760066, 0.09486236, 0.93326654, 0.31482962, 0.96374467, 0.03634771, 0.05099816, 0.1322255 , 0.50590417, 0.81918993, 0.14967056, 0.76917144, 0.50401389, 0.35978655, 0.85351926, 0.19643224, 0.87453091, 0.21389449, 0.39015255, 0.03943358, 0.94713531, 0.7371235 , 0.45292447, 0.81274802, 0.77736136, 0.67821042, 0.2038032 , 0.52985469, 0.35502722, 0.90507388, 0.81105873, 0.63819564, 0.81749468, 0.58585206, 0.33580765, 0.20769787, 0.03885636, 0.49204972, 0.33785215, 0.90457224, 0.38642391, 0.94500146, 0.50176167, 0.26663944, 0.67624895, 0.22594677, 0.29570026, 0.45673858, 0.08399488, 0.49977139, 0.00429661, 0.36698876])]), np.array([[[0.17198702, 0.33934006, 0.5066931 , 0.84139918, 0.54475721, 0.44518522]], [[0.45078077, 0.51860621, 0.58643165, 0.72208252, 0.75760318, 0.56631001]]])),
    (1, 15),
    (60, 60),
    (4.190398263084168, 2.822468818548352)
])
def test_error(model_values, dt, minutes, expect):
    assert error(model_values=model_values, dt=dt, minutes=minutes) == expect
    

@pytest.mark.parametrize('model_values', 'ts', 'expect',[
    (np.array([[[ 0,  3,  5, 15,  2,  3]], [[ 1,  4,  2, 45, 12,  3]]]), 
    np.array([[[0.42087605, 0.74994312, 0.44135151, 0.1785205 , 0.84936434, 0.83721555, 0.42484685, 0.14281674, 0.01244285, 0.94514915, 0.3619434 , 0.6638071 , 0.86247656, 0.78013188, 0.71860495, 0.05871774, 0.90370622, 0.58000835, 0.34467698, 0.94043184, 0.78262761, 0.39710211, 0.35497294, 0.21645378, 0.29074915]], [[0.74023846, 0.31337606, 0.01376574, 0.5722496 , 0.74597571, 0.38459953, 0.69076236, 0.76209921, 0.26052604, 0.90911566, 0.62190726, 0.36775234, 0.99632064, 0.00457101, 0.42828133, 0.63303565, 0.93927696, 0.42881993, 0.24969671, 0.20540724, 0.31256154, 0.70595093, 0.33368909, 0.05422883, 0.48059255]]])),
    (np.array([ 0,  5, 10, 20, 40, 60]), np.linspace(0,60,25)),
    (2457.560550566282, 3.414193912621123)
])
def test_ODE_error(model_values, ts, expect):
    assert error_ODE(model_values=model_values, ts=ts) == expect